spring:
  application:
    name: zipkin

server:
  port: ${SERVER_PORT:9411}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

ribbon:
  eureka:
    enabled: true


