#server.port=8888
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#spring.cloud.config.server.git.uri=https://github.com/AgainstWind/spring-cloud-config-repository

server:
  port: 8888


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  user:
    name: user
    password: password
